name: Build and Test HID Host

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'standard'
        type: choice
        options:
        - standard
        - with-dll
        - simple

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Install HID dependencies
      run: |
        pip install hidapi
        pip install psutil
        
    - name: Install optional dependencies
      continue-on-error: true
      run: |
        pip install GPUtil
        pip install pycaw
        pip install comtypes
        pip install pywin32
        
    - name: Test dependencies
      working-directory: HID-Host
      run: |
        python -c "import hid; print('✓ hidapi works')"
        python -c "import psutil; print('✓ psutil works')"
        python -c "print('✓ Basic imports successful')"
        
    - name: Build Standard
      if: github.event.inputs.build_type == 'standard' || github.event.inputs.build_type == ''
      working-directory: HID-Host
      run: |
        pyinstaller --onefile --console --add-data "hid-config.json;." --collect-all hid --name hid-host-standard hid-host.pyw
        
    - name: Build with DLL Collection
      if: github.event.inputs.build_type == 'with-dll'
      working-directory: HID-Host
      run: |
        pyinstaller --onefile --console --add-data "hid-config.json;." --collect-all hid --collect-binaries hid --name hid-host-dll hid-host.pyw
        
    - name: Build Simple
      if: github.event.inputs.build_type == 'simple'
      working-directory: HID-Host
      run: |
        pyinstaller --onefile --console --add-data "hid-config.json;." --hidden-import hid --name hid-host-simple hid-host.pyw
        
    - name: List build outputs
      working-directory: HID-Host
      run: |
        echo "Build outputs:"
        dir dist
        
    - name: Upload Standard Build
      if: github.event.inputs.build_type == 'standard' || github.event.inputs.build_type == ''
      uses: actions/upload-artifact@v3
      with:
        name: hid-host-standard-windows
        path: HID-Host/dist/hid-host-standard.exe
        
    - name: Upload DLL Build
      if: github.event.inputs.build_type == 'with-dll'
      uses: actions/upload-artifact@v3
      with:
        name: hid-host-dll-windows
        path: HID-Host/dist/hid-host-dll.exe
        
    - name: Upload Simple Build
      if: github.event.inputs.build_type == 'simple'
      uses: actions/upload-artifact@v3
      with:
        name: hid-host-simple-windows
        path: HID-Host/dist/hid-host-simple.exe
        
    - name: Test executable (if exists)
      working-directory: HID-Host/dist
      continue-on-error: true
      run: |
        if (Test-Path "hid-host-standard.exe") {
          echo "Testing standard build..."
          .\hid-host-standard.exe --help
        }
        if (Test-Path "hid-host-dll.exe") {
          echo "Testing DLL build..."
          .\hid-host-dll.exe --help
        }
        if (Test-Path "hid-host-simple.exe") {
          echo "Testing simple build..."
          .\hid-host-simple.exe --help
        }
