name: Build with Included DLL

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install pyinstaller psutil hidapi
        
    - name: Verify DLL exists
      working-directory: HID-Host
      run: |
        if (Test-Path "hidapi.dll") {
          echo "✓ hidapi.dll found in repository"
          $size = (Get-Item "hidapi.dll").Length
          echo "DLL size: $size bytes"
        } else {
          echo "✗ hidapi.dll not found!"
          exit 1
        }
        
    - name: Build HID tools
      working-directory: HID-Host
      run: |
        echo "Building HID-host (GUI) from .pyw file..."
        pyinstaller --onefile --console --add-data "hid-config.json;." --add-binary "hidapi.dll;." --name hid-host hid-host.pyw
        echo "Building HID-CLI from .py file..."
        pyinstaller --onefile --console --add-data "hid-config.json;." --add-binary "hidapi.dll;." --name HID-CLI hid-host.py
        
    - name: Build BLE finder
      run: |
        echo "Building BLE_finder from .pyw file..."
        pyinstaller --onefile --console --name BLE_finder BLE_finder.pyw
        
    - name: Verify HID builds
      working-directory: HID-Host
      run: |
        if (Test-Path "dist/hid-host.exe") {
          echo "✓ HID-host build successful!"
          $size = (Get-Item "dist/hid-host.exe").Length
          echo "HID-host size: $size bytes"
        } else {
          echo "✗ HID-host build failed!"
          exit 1
        }
        if (Test-Path "dist/HID-CLI.exe") {
          echo "✓ HID-CLI build successful!"
          $size = (Get-Item "dist/HID-CLI.exe").Length
          echo "HID-CLI size: $size bytes"
        } else {
          echo "✗ HID-CLI build failed!"
          exit 1
        }
        
    - name: Verify BLE finder build
      run: |
        if (Test-Path "dist/BLE_finder.exe") {
          echo "✓ BLE_finder build successful!"
          $size = (Get-Item "dist/BLE_finder.exe").Length
          echo "BLE_finder size: $size bytes"
        } else {
          echo "✗ BLE_finder build failed!"
          exit 1
        }
        
    - name: Prepare files for upload
      run: |
        mkdir upload-temp
        copy "HID-Host\dist\hid-host.exe" "upload-temp\"
        copy "HID-Host\dist\HID-CLI.exe" "upload-temp\"
        copy "dist\BLE_finder.exe" "upload-temp\"
        echo "Files prepared in upload-temp directory:"
        dir upload-temp
        
    - name: Upload all tools
      uses: actions/upload-artifact@v4
      with:
        name: hid-tools-complete
        path: upload-temp/*
