name: Build HID Host with DLL Fix

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install pyinstaller psutil hidapi
        
    - name: Download hidapi DLL manually
      run: |
        echo "Downloading hidapi DLL from official source..."
        # Download hidapi DLL from official releases
        Invoke-WebRequest -Uri "https://github.com/libusb/hidapi/releases/download/hidapi-0.14.0/hidapi-win.zip" -OutFile "hidapi.zip"
        Expand-Archive -Path "hidapi.zip" -DestinationPath "hidapi-temp"
        
        # Find and copy the DLL
        $dll = Get-ChildItem -Path "hidapi-temp" -Filter "*.dll" -Recurse | Select-Object -First 1
        if ($dll) {
          echo "Found DLL: $($dll.FullName)"
          Copy-Item $dll.FullName "HID-Host/hidapi.dll"
          echo "Copied DLL to HID-Host directory"
        } else {
          echo "No DLL found in download"
        }
        
    - name: Build with explicit DLL inclusion
      working-directory: HID-Host
      run: |
        echo "Building with explicit hidapi.dll inclusion..."
        
        # Check if we have the DLL
        if (Test-Path "hidapi.dll") {
          echo "Using downloaded DLL"
          pyinstaller --onefile --console --add-data "hid-config.json;." --add-binary "hidapi.dll;." --collect-all hid --name hid-host-fixed hid-host.pyw
        } else {
          echo "No DLL found, using collect-all method"
          pyinstaller --onefile --console --add-data "hid-config.json;." --collect-all hid --name hid-host-basic hid-host.pyw        }
        
    - name: Alternative build with different hidapi package
      working-directory: HID-Host  
      continue-on-error: true
      run: |
        echo "Trying alternative hidapi package..."
        pip uninstall hidapi -y
        pip install hid
        pyinstaller --onefile --console --add-data "hid-config.json;." --collect-all hid --name hid-host-alt hid-host.pyw
        
    - name: List all builds
      working-directory: HID-Host
      run: |
        echo "=== BUILD RESULTS ==="
        if (Test-Path "dist") {
          Get-ChildItem dist | Format-Table Name,Length
        }
        
    - name: Upload all builds
      uses: actions/upload-artifact@v3
      with:
        name: hid-host-all-builds
        path: HID-Host/dist/*.exe
